services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    restart: unless-stopped
